id: d21f0fb9e6af4b25ba0609bfb6343ded
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_325-The_Verses_of_Naga_King_Drum-v2
  language: en
  author: ''
  volume: {}
